import '~/styles/globals.css'

import { Inter } from 'next/font/google'
import { headers } from 'next/headers'

import { TRPCReactProvider } from '~/trpc/react'
import { cn } from '~/lib/utils'
import { LanguageProvider } from '~/contexts/language'

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-sans',
})

export const metadata = {
  title: 'Create T3 App',
  description: 'Generated by create-t3-app',
  icons: [{ rel: 'icon', url: '/favicon.ico' }],
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning={true}
        className={cn(
          'min-h-screen bg-background font-sans text-primary antialiased',
          inter.variable,
        )}
      >
        <TRPCReactProvider headers={headers()}>
          <LanguageProvider>{children}</LanguageProvider>
        </TRPCReactProvider>
      </body>
    </html>
  )
}
